safe:        false
baseurl:     /
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
safe:        true
lsi:         false
highlighter: pygments
markdown:    Kramdown
permalink:   /:categories/:year/:month/:day/:title/
encoding:    utf-8

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
