##
# Site settings
title: Steven Brunwasser
description: > # this means to ignore newlines until "baseurl:"
  A software developer in the San Francisco Bay Area since 2014.
  Focuses on developing functional and testable software.

url: "http://brun.ws" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
permalink:   /:categories/:year/:month/:day/:title


##
# Additional Data
online_profiles:
  - network: GitHub
    username: altece
    url: https://github.com/altece
  - network: Twitter
    username: altece
    url: https://twitter.com/altece
  - network: LinkedIn
    username: stevebrun
    url: https://linkedin.com/in/stevebrun


recaptcha_key: 6Ld8-UYUAAAAAFuFEGvFJAeWGfalxtgBSv4bdeqA
recaptcha_server: http://verify.brun.ws/request_email

##
# Build settings
source:      .
destination: ./_site
encoding: utf-8
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-gist
  - jekyll-relative-links


